TRANSLATIONS = {
    "ru": {
        "app_title": "WISELY", "role_question": "Кто вы?", "role_student": "Я ученик", "role_teacher": "Я учитель",
        "nav_dashboard": "Главная", "nav_subjects": "Мои предметы", "nav_homework": "Домашние задания", "nav_progress": "Мой прогресс",
        "dashboard_welcome": "С возвращением!", "dashboard_today": "Сегодня стоит повторить",
        "subjects_title": "Какие предметы хочешь изучать глубже?", "subjects_subtitle": "Можно выбрать несколько — мы подстроим программу под тебя",
        "subject_algebra": "Алгебра", "subject_geometry": "Геометрия", "subject_law": "Основы права", "subject_physics": "Физика", "subject_chemistry": "Химия", "subject_biology": "Биология",
        "continue_btn": "Продолжить", "back_btn": "Назад", "back_short": "← Назад", "task_check": "Проверить", "task_correct": "Отлично, верно!", "task_incorrect": "Пока не то — попробуй ещё раз", "task_next": "Следующее задание", "task_placeholder": "Введите ваш ответ", "topics_empty": "В этой теме пока нет заданий", "topic_completed": "Тема пройдена", "correct_answer_label": "Правильный ответ", "step_label": "Шаг",
        "ai_check_title": "Проверка решения", "ai_no_photo": "Фото ещё не выбрано", "ai_upload_btn": "📷 Загрузить фото", "ai_analyzing": "Анализируем решение…", "ai_unreadable": "Не удалось распознать фото — переснимите, пожалуйста.", "ai_failed": "Не получилось проверить.", "ai_error_reason": "Причина: {reason}", "ai_retry": "Попробовать снова", "ai_verdict_correct": "✓ Решение правильное", "ai_verdict_issues": "⚠ Есть замечания",
        "mistake_calculation": "Ошибка в вычислениях", "mistake_formula": "Неверная формула", "mistake_concept": "Пробел в понимании темы", "mistake_formatting": "Проблема с оформлением",
        "dashboard_welcome_back": "С возвращением!", "rec_start": "🎯 Начни с первой темы — мы подстроимся под твои результаты.", "rec_repeat": "🎯 Стоит повторить тему «{topic}»", "rec_practice": "🎯 Потренируйся ещё в теме «{topic}»", "rec_next": "🎯 Отличный прогресс! Можно двигаться дальше.",
        "task_check_photo": "📷 Проверить по фото (ИИ)", "logout_btn": "Выйти", "logout_confirm_title": "Выйти из аккаунта?", "logout_confirm_text": "Прогресс будет сброшен, и вы вернётесь к выбору роли.", "homework_title": "Домашняя практика", "homework_subtitle": "Закрепи темы короткими сериями заданий — Окто подскажет, с чего начать.", "homework_tasks": "{count} заданий в серии", "homework_open": "Начать", "progress_title": "Мой прогресс", "progress_subtitle": "Следи за результатами и возвращайся к темам, которые требуют внимания.", "progress_average": "средний результат", "progress_completed": "тем завершено", "progress_mistakes": "ошибок всего", "progress_done": "Тема завершена", "progress_in_progress": "В процессе", "activity_title": "Серия активности", "streak_current": "Сейчас: {days} дн. · Лучшая: {best} дн.", "mon": "Пн", "tue": "Вт", "wed": "Ср", "thu": "Чт", "fri": "Пт", "sat": "Сб", "sun": "Вс", "teacher_title": "Кабинет учителя", "teacher_subtitle": "Обзор активности учеников и прогресса по темам.", "teacher_topics": "Прогресс по темам", "teacher_learners": "Серии учеников", "teacher_grade": "класс", "teacher_learner_detail": "Попыток: {attempts} · Средний балл: {average}%", "teacher_streak": "Серия: {days} дн. · Рекорд: {best} дн.", "teacher_students": "учеников", "teacher_attempts": "попыток", "teacher_average": "средний балл", "teacher_topic_detail": "Попыток: {attempts}", "topic_todo": "Раздел темы готовится", "solution_ready": "Решение будет показано здесь после выбора задания.", "mascot_name": "Окто"
    },
    "kz": {
        "app_title": "WISELY", "role_question": "Sız kımsız?", "role_student": "Men oquşymyn", "role_teacher": "Men mūğalımmın",
        "nav_dashboard": "Basty bet", "nav_subjects": "Menıñ pänderım", "nav_homework": "Üi tapsyrmalary", "nav_progress": "Menıñ ilgerıleuım",
        "dashboard_welcome": "Qaita oralğanyña quanyştymyz!", "dashboard_today": "Bügın qaitalauğa tiıs",
        "subjects_title": "Qai pänderdı tereñırek oqyğyñ keledı?", "subjects_subtitle": "Bırneşeuın tandauğa bolady — bağdarlamany sağan retteimız",
        "subject_algebra": "Algebra", "subject_geometry": "Geometriya", "subject_law": "Qūqyq negızderı", "subject_physics": "Fizika", "subject_chemistry": "Ximiya", "subject_biology": "Biologiya",
        "continue_btn": "Jalğastyru", "back_btn": "Artqa", "back_short": "← Artqa", "task_check": "Tekseru", "task_correct": "Tamaşa, dūrys!", "task_incorrect": "Äzırge olai emes — tağy bır ret kör", "task_next": "Kelesı tapsyrma", "task_placeholder": "Jauabyñdy jazyñ", "topics_empty": "Äzırge būl taqyryp boiynşa tapsyrmalar joq", "topic_completed": "Taqyryp ötıldı", "correct_answer_label": "Dūrys jauap", "step_label": "Qadam",
        "ai_check_title": "Şeşımdı tekseru", "ai_no_photo": "Foto älı tañdalmağan", "ai_upload_btn": "📷 Foto jükteu", "ai_analyzing": "Şeşım taldanyp jatyr…", "ai_unreadable": "Fotony tanu mümkın bolmady — qaita tüsır.", "ai_failed": "Tekseru oryndalmady.", "ai_error_reason": "Sebebı: {reason}", "ai_retry": "Qaita sınap köru", "ai_verdict_correct": "✓ Şeşım dūrys", "ai_verdict_issues": "⚠ Eskertuler bar",
        "mistake_calculation": "Esepteudegı qate", "mistake_formula": "Dūrys emes formula", "mistake_concept": "Taqyrypty tüsınudegı alşaqtyq", "mistake_formatting": "Räsımdeudegı mäsele",
        "dashboard_welcome_back": "Qaita oralğanyña quanyştymyz!", "rec_start": "🎯 Bırınşı taqyryptan basta — nätijeñe qarai beýımdeimiz.", "rec_repeat": "🎯 «{topic}» taqyrybyn qaitalağan jön", "rec_practice": "🎯 «{topic}» taqyrybynda tağy jattyğu jasa", "rec_next": "🎯 Tamaşa ilgerıleu! Kelesı taqyrypta ötuge bolady.",
        "task_check_photo": "📷 Foto arqyly tekseru (Jİ)", "logout_btn": "Şyğu", "logout_confirm_title": "Akkaunttan şyğu?", "logout_confirm_text": "Ilgerıleu tazalanady, röl tañdauğa qaitasyñ.", "homework_title": "Üi tapsyrmasy", "homework_subtitle": "Taqyrypty qısqa tapsyrmalar seriyasy arqyly bekıt — Okto bastaudy körsetedı.", "homework_tasks": "Seriyada {count} tapsyrma", "homework_open": "Bastau", "progress_title": "Menıñ ilgerıleuım", "progress_subtitle": "Nätijeñdı baqyla jäne köbırek nazar qajet taqyryptarğa oral.", "progress_average": "ortaşa nätije", "progress_completed": "taqyryp ayaqtaldy", "progress_mistakes": "jalpy qate", "progress_done": "Taqyryp ayaqtaldy", "progress_in_progress": "Jürgızılude", "activity_title": "Belsendılık seriyasy", "streak_current": "Qazır: {days} kün · Eñ jaqsysy: {best} kün", "mon": "Dü", "tue": "Se", "wed": "Sä", "thu": "Be", "fri": "Ju", "sat": "Se", "sun": "Je", "teacher_title": "Mūğalım kabınetı", "teacher_subtitle": "Oquşylardyñ belsendılıgı men taqyryptar boiynşa ilgerıleuı.", "teacher_topics": "Taqyryp boiynşa ilgerıleu", "teacher_learners": "Oquşylardyñ seriyalary", "teacher_grade": "synyp", "teacher_learner_detail": "Äreket: {attempts} · Ortaşa ball: {average}%", "teacher_streak": "Seriya: {days} kün · Rekord: {best} kün", "teacher_students": "oquşy", "teacher_attempts": "äreket", "teacher_average": "ortaşa ball", "teacher_topic_detail": "Äreket: {attempts}", "topic_todo": "Taqyryp bölındeı jürgızılude", "solution_ready": "Tapsyrma tañdalğannan keiın şeşım osy jerde körsetıledı.", "mascot_name": "Okto"
    },
}
